name: sds_new
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.1
  image_picker: ^0.8.5
  get: ^4.6.5
  flutter_screenutil: ^5.8.4
  flutter_native_splash: ^2.2.0+1
  path_provider: ^2.0.10
  csv: ^5.0.1
  file_picker: ^4.5.1
  webview_flutter: ^3.0.4




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - image/
    - recommend_file/
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: font/NotoSansKR/NotoSansKR-Black.otf
          weight: 900
        - asset: font/NotoSansKR/NotoSansKR-Bold.otf
          weight: 700
        - asset: font/NotoSansKR/NotoSansKR-Light.otf
          weight: 300
        - asset: font/NotoSansKR/NotoSansKR-Medium.otf
          weight: 500
        - asset: font/NotoSansKR/NotoSansKR-Regular.otf
          weight: 400
        - asset: font/NotoSansKR/NotoSansKR-Thin.otf
          weight: 100

    - family: SpoqaHanSansNeo
      fonts:
        - asset: font/SpoqaHanSansNeo/SpoqaHanSansNeo-Bold.otf
          weight: 700
        - asset: font/SpoqaHanSansNeo/SpoqaHanSansNeo-Light.otf
          weight: 300
        - asset: font/SpoqaHanSansNeo/SpoqaHanSansNeo-Medium.otf
          weight: 500
        - asset: font/SpoqaHanSansNeo/SpoqaHanSansNeo-Regular.otf
          weight: 400
        - asset: font/SpoqaHanSansNeo/SpoqaHanSansNeo-Thin.otf
          weight: 100

    - family: NotoSans
      fonts:
        - asset: font/NotoSans/NotoSans-Bold.ttf
          weight: 700
        - asset: font/NotoSans/NotoSans-Medium.ttf
          weight: 500
        - asset: font/NotoSans/NotoSans-Regular.ttf
          weight: 400
        - asset: font/NotoSans/NotoSans-SemiBold.ttf
          weight: 600

    - family: Bamin
      fonts:
        - asset: font/BMEuljiro10yearslaterOTF.otf

#flutter_native_splash:
#  color: "#7b0cbb"
#  image: image/chef.png
#  fullscreen: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
